package com.example.iweibo.util;

import com.example.iweibo.R;

public class IDs {
	public static int[] emtion_id = {
			R.drawable.pcmoren_huaixiao_org, R.drawable.pcmoren_tian_org, R.drawable.pcmoren_wu_org,
			R.drawable.moren_yunbei_org, R.drawable.moren_xiaoerbuyu_org, R.drawable.moren_feijie_org,
			R.drawable.moren_chongjing_org, R.drawable.moren_bbjdnew_org, R.drawable.huanglianwx_org,
			R.drawable.pcmoren_cool2017_org, R.drawable.tootha_org, R.drawable.laugh, R.drawable.tza_org,
			R.drawable.kl_org, R.drawable.wabi_org, R.drawable.cj_org, R.drawable.shamea_org, R.drawable.zy_org,
			R.drawable.bz_org, R.drawable.bs2_org, R.drawable.lovea_org, R.drawable.sada_org, R.drawable.heia_org,
			R.drawable.qq_org, R.drawable.sb_org, R.drawable.mb_org, R.drawable.landeln_org, R.drawable.yhh_org,
			R.drawable.zhh_org, R.drawable.x_org, R.drawable.cry, R.drawable.wq_org, R.drawable.t_org,
			R.drawable.haqianv2_org, R.drawable.bba_org, R.drawable.angrya_org, R.drawable.yw_org, R.drawable.cza_org,
			R.drawable.img_88_org, R.drawable.sk_org, R.drawable.sweata_org, R.drawable.kunv2_org,
			R.drawable.huangliansj_org, R.drawable.money_org, R.drawable.sw_org, R.drawable.huanglianse_org,
			R.drawable.hatea_org, R.drawable.gza_org, R.drawable.dizzya_org, R.drawable.bs_org, R.drawable.crazya_org,
			R.drawable.h_org, R.drawable.yx_org, R.drawable.numav2_org, R.drawable.hufen_org, R.drawable.hearta_org,
			R.drawable.unheart, R.drawable.pig, R.drawable.panda_org, R.drawable.rabbit_org, R.drawable.ok_org,
			R.drawable.ye_org, R.drawable.good_org, R.drawable.buyao_org, R.drawable.z2_org, R.drawable.come_org,
			R.drawable.sad_org, R.drawable.shenshou_org, R.drawable.horse2_org, R.drawable.j_org, R.drawable.fuyun_org,
			R.drawable.geiliv2_org, R.drawable.wg_org, R.drawable.vw_org, R.drawable.huatongv2_org,
			R.drawable.cakev2_thumb, R.drawable.ad_new0902_org, R.drawable.doge_org, R.drawable.mm_org,
			R.drawable.moren_hashiqi_org, R.drawable.xiaohuangren_jiandaoshou_org, R.drawable.xiaohuangren_gaoxing_org,
			R.drawable.xiaoku_org, R.drawable.pcmoren_tanshou_org, R.drawable.pcmoren_baobao_org,
			R.drawable.pcmoren_guile_org, R.drawable.moren_chiguaqunzhong_org, R.drawable.dorachijing_org,
			R.drawable.xiaohuangren_huaixiao_org, R.drawable.bhsj5_nainai_org, R.drawable.xman_kuaiyin_org,
			R.drawable.xman_baofengnv_org, R.drawable.mango_07_org, R.drawable.mango_12_org, R.drawable.mango_02_org,
			R.drawable.mango_03_org, R.drawable.mango_11_org, R.drawable.yangniandj_org, R.drawable.watermelon,
			R.drawable.football, R.drawable.mothersday_org, R.drawable.carnation_org, R.drawable.soap_org,
			R.drawable.youqian_org, R.drawable.earth1r_org, R.drawable.flag_org, R.drawable.lxhxuyuan_org,
			R.drawable.fan, R.drawable.zhaji_org, R.drawable.snow_org, R.drawable.mashangyouduixiang_org,
			R.drawable.madaochenggong_org, R.drawable.hongyun_org, R.drawable.hongbaofei2014_org,
			R.drawable.alizuoguiliannew_org, R.drawable.aliwanew_org, R.drawable.xklzhuanquan_org,
			R.drawable.kxwanpi_org, R.drawable.bmkeai_org, R.drawable.boaini_org, R.drawable.lxhzhuanfa_org,
			R.drawable.lxhdeyidixiao_org, R.drawable.ppbguzhang_org, R.drawable.dintuizhuang_org,
			R.drawable.moczhuanfa_org, R.drawable.ltqiekenao_org, R.drawable.gangnamstyle_org, R.drawable.lxhwahaha_org,
			R.drawable.zy_org, R.drawable.qq_org, R.drawable.mb_org, R.drawable.sb_org, R.drawable.sdz_org,
			R.drawable.sw_org, R.drawable.kl_org, R.drawable.h_org, R.drawable.t_org, R.drawable.wq_org,
			R.drawable.sk_org, R.drawable.laugh, R.drawable.x_org, R.drawable.yhh_org, R.drawable.zhh_org,
			R.drawable.yw_org, R.drawable.yx_org, R.drawable.d_org, R.drawable.money_org, R.drawable.bs_org,
			R.drawable.bs2_org, R.drawable.img_88_org, R.drawable.cj_org, R.drawable.bz_org, R.drawable.cry,
			R.drawable.fn_org, R.drawable.gm_org, R.drawable.come_org, R.drawable.good_org, R.drawable.ha_org,
			R.drawable.ok_org, R.drawable.o_org, R.drawable.sad_org, R.drawable.ws_org, R.drawable.z2_org,
			R.drawable.ye_org, R.drawable.bad_org, R.drawable.buyao_org, R.drawable.numav2_org, R.drawable.kunv2_org,
			R.drawable.lazhuv2_org, R.drawable.haqianv2_org, R.drawable.huanglianwx_org, R.drawable.landeln_org,
			R.drawable.huangliansj_org, R.drawable.huanglianse_org, R.drawable.wabi_org, R.drawable.shayan_org,
			R.drawable.dalian_org, R.drawable.zuoyi_org, R.drawable.xiaoku_org, R.drawable.tza_org,
			R.drawable.tootha_org, R.drawable.sweata_org, R.drawable.shamea_org, R.drawable.sada_org,
			R.drawable.lovea_org, R.drawable.heia_org, R.drawable.hearta_org, R.drawable.hatea_org, R.drawable.gza_org,
			R.drawable.dizzya_org, R.drawable.cza_org, R.drawable.crazya_org, R.drawable.bba_org, R.drawable.angrya_org,
			R.drawable.right_org, R.drawable.left_org, R.drawable.dorahaose_org, R.drawable.dorahaipa_org,
			R.drawable.dorachijing_org, R.drawable.dorahan_org, R.drawable.jqmweixiao_org, R.drawable.jqmbwtxing_org,
			R.drawable.jiqimaojingxiang_org, R.drawable.jiqimaodaxiong_org, R.drawable.jiqimaopanghu_org,
			R.drawable.jiqimaoxiaofu_org, R.drawable.dora_xiao_org, R.drawable.dora_wunai_org,
			R.drawable.dora_meiwei_org, R.drawable.dora_kaixin_org, R.drawable.dora_qinqin_org,
			R.drawable.xiaohuangren_weixiao_org, R.drawable.xiaohuangren_buxie_org, R.drawable.xiaohuangren_buxie_org,
			R.drawable.xiaohuangren_baiyan_org, R.drawable.xiaohuangren_gaoxing_org, R.drawable.xiaohuangren_wunai_org,
			R.drawable.xiaohuangren_jingya_org, R.drawable.xiaohuangren_weiqu_org,
			R.drawable.xiaohuangren_jiandaoshou_org, R.drawable.xiaohuangren_deyi_org,
			R.drawable.xiaohuangren_huaixiao_org, R.drawable.bmzuocao_org, R.drawable.bmzhuakuang_org,
			R.drawable.bmzhongqiang_org, R.drawable.bmzhenjing_org, R.drawable.bmzan_org, R.drawable.bmxiyue_org,
			R.drawable.bmxingwu_org, R.drawable.bmxingfen_org, R.drawable.bmxielei_org, R.drawable.bmwabikong_org,
			R.drawable.bmtushetou_org, R.drawable.bmtucao_org, R.drawable.bmtousu_org, R.drawable.bmtiaosheng_org,
			R.drawable.bmtiaopi_org, R.drawable.bmtaolun_org, R.drawable.bmtaitui_org, R.drawable.bmsikao_org,
			R.drawable.bmshengqi_org, R.drawable.bmqinwen_org, R.drawable.bmqingxing_org, R.drawable.bmneihan_org,
			R.drawable.bmmanglu_org, R.drawable.bmluanru_org, R.drawable.bmluanmeng_org, R.drawable.bmliulei_org,
			R.drawable.bmliukoushui_org, R.drawable.bmliubiti_org, R.drawable.bmliguo_org, R.drawable.bmliezui_org,
			R.drawable.bmlaladui_org, R.drawable.bmkusu_org, R.drawable.bmkuqi_org, R.drawable.bmkubi_org,
			R.drawable.bmkoushao_org, R.drawable.bmkeai_org, R.drawable.bmjinzhang_org, R.drawable.bmjingya_org,
			R.drawable.bmjingxia_org, R.drawable.bmjiaolv_org, R.drawable.bmhuixinxiao_org, R.drawable.bmhuaixiao_org,
			R.drawable.bmhuachi_org, R.drawable.bmhoulianpi_org, R.drawable.bmhaoba_org, R.drawable.bmhaipa_org,
			R.drawable.bmguilian_org, R.drawable.bmgudu_org, R.drawable.bmgaoxing_org, R.drawable.bmgaoguai_org,
			R.drawable.bmganxiao_org, R.drawable.bmgandong_org, R.drawable.bmfenmen_org, R.drawable.bmfandui_org,
			R.drawable.bmduobu_org, R.drawable.bmding_org, R.drawable.bmdeyi_org, R.drawable.bmdese_org,
			R.drawable.bmdaxiao_org, R.drawable.bmdaku_org, R.drawable.bmdajiao_org, R.drawable.bmchijing_org,
			R.drawable.bmchan_org, R.drawable.bmcaise_org, R.drawable.bmbinfen_org, R.drawable.bmbianshen_org,
			R.drawable.bmbeicui_org, R.drawable.bmbaonu_org, R.drawable.bmaoye_org, R.drawable.bmanshuang_org,
			R.drawable.xklbainian_org, R.drawable.xklgongxi_org, R.drawable.xklfacai_org, R.drawable.xklbianpao_org,
			R.drawable.xklxiaxue_org, R.drawable.xklsahua_org, R.drawable.xklrengtangdou_org, R.drawable.xklniu_org,
			R.drawable.xklnipaiyi_org, R.drawable.xkldacha_org, R.drawable.xklbanyun2_org, R.drawable.xklbanyun1_org,
			R.drawable.dadazhuanquan_org, R.drawable.dadayangge_org, R.drawable.dadadenglong_org,
			R.drawable.xklzhui_org, R.drawable.xklyongbao_org, R.drawable.xklqinqin_org, R.drawable.xklkun_org,
			R.drawable.xkldadaxihuan_org, R.drawable.xkldadatushetou_org, R.drawable.xkldadahuaixiao_org,
			R.drawable.xkldadaheian_org, R.drawable.xklchixigua_org, R.drawable.kxlyun_org, R.drawable.xklzhuakuang_org,
			R.drawable.xklzhayan_org, R.drawable.xklyaoweiba_org, R.drawable.xkltoukan_org, R.drawable.xkltangdou_org,
			R.drawable.xkljiong_org, R.drawable.xklfumo_org, R.drawable.xklbenpao_org, R.drawable.xklbeizhua_org,
			R.drawable.xklbeidian_org, R.drawable.xlknuhuo_org, R.drawable.xklzhuanquan_org, R.drawable.xklxi_org,
			R.drawable.xklweiqu_org, R.drawable.xklshihua_org, R.drawable.xklqidai_org, R.drawable.xklnielian_org,
			R.drawable.xklluguo_org, R.drawable.xklhahaha_org, R.drawable.xklding_org, R.drawable.lttickets_org,
			R.drawable.ltwuyi_org, R.drawable.ltxinnianhao_org, R.drawable.lttrain_org, R.drawable.lthongbao_org,
			R.drawable.ltrock_org, R.drawable.lthalloween_org, R.drawable.ltgood_org, R.drawable.ltgangnamstyle_org,
			R.drawable.lteating_org, R.drawable.ltzuiyou_org, R.drawable.ltqiekenao_org, R.drawable.ltfankun_org,
			R.drawable.ltchuoxia_org, R.drawable.ltbixue_org, R.drawable.ltyinxian_org, R.drawable.ltyaobai_org,
			R.drawable.ltxiu_org, R.drawable.ltshanxia_org, R.drawable.ltpaishou_org, R.drawable.ltdanteng_org,
			R.drawable.ltsahua_org, R.drawable.ltmuqinjie_org, R.drawable.ltwabi_org, R.drawable.lehaqian_org,
			R.drawable.ltleimu_org, R.drawable.ltlei_org, R.drawable.ltzhongqiang_org, R.drawable.lterduo_org,
			R.drawable.ltding_org, R.drawable.ltqianshui_org, R.drawable.ltpaizhuodaxiao_org, R.drawable.ltheixian_org,
			R.drawable.ltpenxue_org, R.drawable.ltjuhan_org, R.drawable.ltyihuo_org, R.drawable.ltfuyun_org,
			R.drawable.ltxiaohua_org, R.drawable.ltpen_org, R.drawable.ltxue_org, R.drawable.ltzhuanfa_org,
			R.drawable.lttoukui_org, R.drawable.ltjingxia_org, R.drawable.ltjiong_org, R.drawable.lthuifeiyanmie_org,
			R.drawable.ltbengfeng_org, R.drawable.lttu_org, R.drawable.ltchuipaopao_org, R.drawable.ltxia_org,
			R.drawable.mango_12_org, R.drawable.mango_11_org, R.drawable.mango_10_org, R.drawable.mango_09_org,
			R.drawable.mango_08_org, R.drawable.mango_07_org, R.drawable.mango_06_org, R.drawable.mango_05_org,
			R.drawable.mango_04_org, R.drawable.mango_03_org, R.drawable.mango_02_org, R.drawable.mango_01_org,
			R.drawable.fansclub_org, R.drawable.fansyingyuan_org, R.drawable.tffans_org, R.drawable.tfkai_org,
			R.drawable.tfyuan_org, R.drawable.tfqian_org, R.drawable.newt_org, R.drawable.newf_org,
			R.drawable.weibob_org, R.drawable.weiboo_org, R.drawable.newy_org, R.drawable.news_org,
			R.drawable.dinkankan_org, R.drawable.dinshuohua_org, R.drawable.dindongshengdanliwu_org,
			R.drawable.dinjenzhaocaimao_org, R.drawable.dinjenfudao_org, R.drawable.dindongzhaocaimao_org,
			R.drawable.dindongxmas_org, R.drawable.dindongshengdanshu_org, R.drawable.dindongjenshengdanben_org,
			R.drawable.dindongjenpaozhu_org, R.drawable.dindongjenliwuhe_org, R.drawable.dindongjenliwu_org,
			R.drawable.dindongjenbianshen_org, R.drawable.dindonghongbao_org, R.drawable.dindongcaishen_org,
			R.drawable.dinzhuanzhuan_org, R.drawable.dinzhuangqiang_org, R.drawable.dinzhuakuang_org,
			R.drawable.dinzanhao_org, R.drawable.dinxinxi_org, R.drawable.dinxingfen_org, R.drawable.dintuizhuang_org,
			R.drawable.dintiano_org, R.drawable.dintantan_org, R.drawable.dinshuijiao_org, R.drawable.dinshuai_org,
			R.drawable.dinshanbi_org, R.drawable.dinqinqin_org, R.drawable.dinpaishou_org, R.drawable.dinnu_org,
			R.drawable.dinmotou_org, R.drawable.dinliuxue_org, R.drawable.dinlihai_org, R.drawable.dinlianhong_org,
			R.drawable.dinlei_org, R.drawable.dinjianxiang_org, R.drawable.dinhuishou_org, R.drawable.dinhuazhuang_org,
			R.drawable.dinhe_org, R.drawable.dinhan_org, R.drawable.dinhaixiu_org, R.drawable.dinguilian_org,
			R.drawable.dinguale_org, R.drawable.dinfenshenb_org, R.drawable.dinfenshena_org, R.drawable.dindiandang_org,
			R.drawable.dindaixiong_org, R.drawable.dinchi_org, R.drawable.dinbianshen_org, R.drawable.dinbianlian_org,
			R.drawable.dinbaiqi_org, R.drawable.dinaini_org, R.drawable.aligongyi_org, R.drawable.newalidese_org,
			R.drawable.alizuoguiliannew_org, R.drawable.alizhuinew_org, R.drawable.alizhuanquankunew_org,
			R.drawable.alizhuannew_org, R.drawable.aliyumengnew_org, R.drawable.aliyuanbaonew_org,
			R.drawable.aliyaohuangnew_org, R.drawable.alixuxunew_org, R.drawable.alixiunew_org,
			R.drawable.alixiaosilenew_org, R.drawable.alixiaonew_org, R.drawable.alixianzhuozinew_org,
			R.drawable.alixianhuanew_org, R.drawable.alixiangnew_org, R.drawable.alixianew_org, R.drawable.aliwanew_org,
			R.drawable.alituxuenew_org, R.drawable.alitoukannew_org, R.drawable.alisongliwunew_org,
			R.drawable.alishuinew_org, R.drawable.alishuaishounew_org, R.drawable.alishuainew_org,
			R.drawable.alisaqiannew_org, R.drawable.aliqiunew_org, R.drawable.aliqinyigenew_org,
			R.drawable.aliqianzounew_org, R.drawable.alipunew_org, R.drawable.alipudaonew_org,
			R.drawable.alipiaonew_org, R.drawable.alipiaoguonew_org, R.drawable.alipengtinew_org,
			R.drawable.alipaipaishounew_org, R.drawable.alininew_org, R.drawable.alinaoqiangnew_org,
			R.drawable.alimomotounew_org, R.drawable.aliliunew_org, R.drawable.alilaipinew_org,
			R.drawable.alilaibanew_org, R.drawable.alijiongnew_org, R.drawable.alijingnew_org,
			R.drawable.alijiayounew_org, R.drawable.alijiangshitiaonew_org, R.drawable.alihulaquannew_org,
			R.drawable.alihuaquanquannew_org, R.drawable.alihuanhunew_org, R.drawable.alihuaixiaonew_org,
			R.drawable.aliguiqiunew_org, R.drawable.alifengzhengnew_org, R.drawable.alifeinew_org,
			R.drawable.alifanbaiyannew_org, R.drawable.alidingqinew_org, R.drawable.alidiantounew_org,
			R.drawable.alidesenew_org, R.drawable.alidalanqiunew_org, R.drawable.alidagunnew_org,
			R.drawable.alidachinew_org, R.drawable.alicainew_org, R.drawable.alibunaifannew_org,
			R.drawable.alibumanew_org, R.drawable.alibiechaonew_org, R.drawable.alibianpaonew_org,
			R.drawable.alibaoyibaonew_org, R.drawable.alibainiannew_org, R.drawable.ali88new_org, R.drawable.zk_org,
			R.drawable.wq2_org, R.drawable.q2_org, R.drawable.mh_org, R.drawable.m2_org, R.drawable.j3_org,
			R.drawable.h2_org, R.drawable.f_org, R.drawable.c_org, R.drawable.bz3_org, R.drawable.bgp_org,
			R.drawable.bohaixiu_org, R.drawable.bohaha_org, R.drawable.bochimian_org, R.drawable.bocalei_org,
			R.drawable.bobuyaoa_org, R.drawable.bobianshen_org, R.drawable.bobengkui_org, R.drawable.bobai_org,
			R.drawable.boaini_org, R.drawable.todawoa_org, R.drawable.longniantoto_org, R.drawable.bobolongnian_org,
			R.drawable.totowuliao_org, R.drawable.totowozuiyaogun_org, R.drawable.totoshuluo_org,
			R.drawable.totoshuijiao_org, R.drawable.totoshuaitoufa_org, R.drawable.totopiaoguo_org,
			R.drawable.totokuanghan_org, R.drawable.totohaolei_org, R.drawable.bobozhuakuang_org,
			R.drawable.boboyiwen_org, R.drawable.bobopaomeiyan_org, R.drawable.bobomobai_org, R.drawable.bobojiujie_org,
			R.drawable.bobobuyaoa_org, R.drawable.bobobulini_org, R.drawable.totoyouai_org, R.drawable.totoyes_org,
			R.drawable.tototingge_org, R.drawable.totonu_org, R.drawable.totoleigu_org, R.drawable.totojixiao_org,
			R.drawable.totoheixianpaoqian_org, R.drawable.boboxianhua_org, R.drawable.boboweiqu_org,
			R.drawable.bobotoukan_org, R.drawable.bobotiaopi_org, R.drawable.boboshengmenqi_org, R.drawable.boboren_org,
			R.drawable.bobopaopaotang_org, R.drawable.bobook_org, R.drawable.bobohi_org, R.drawable.bobofeiwen_org,
			R.drawable.bobochixigua_org, R.drawable.bobochijing_org, R.drawable.bobochifan_org, R.drawable.doge_org,
			R.drawable.mm_org, R.drawable.moren_hashiqi_org, R.drawable.zz2_org, R.drawable.rabbit_org,
			R.drawable.horse2_org, R.drawable.fuyun_org, R.drawable.geiliv2_org, R.drawable.kawayi_org,
			R.drawable.panda_org, R.drawable.hufen_org, R.drawable.wg_org, R.drawable.rjd_org, R.drawable.otm_org,
			R.drawable.vw_org, R.drawable.unheart, R.drawable.rw_org, R.drawable.j_org, R.drawable.orz1_org,
			R.drawable.z_org, R.drawable.s2_org, R.drawable.pig, R.drawable.sx_org, R.drawable.kl2_org,
			R.drawable.s_org, R.drawable.yellowcard, R.drawable.redcard, R.drawable.twh_org, R.drawable.bingo_org,
			R.drawable.zt_org, R.drawable.img_03_org, R.drawable.img_04_org, R.drawable.img_05_org,
			R.drawable.img_06_org, R.drawable.img_01_org, R.drawable.tuan_org, R.drawable.yuan_org,
			R.drawable.kissboy_org, R.drawable.kissgirl_org, R.drawable.zhajibeer_org, R.drawable.guilian_org,
			R.drawable.twot_org, R.drawable.zero_org, R.drawable.two_org, R.drawable.three_org, R.drawable.six_org,
			R.drawable.seven_org, R.drawable.one_org, R.drawable.nine_org, R.drawable.four_org, R.drawable.five_org,
			R.drawable.eight_org, R.drawable.newz_org, R.drawable.newy_org, R.drawable.newx_org, R.drawable.newv_org,
			R.drawable.newu_org, R.drawable.newt_org, R.drawable.news_org, R.drawable.newr_org, R.drawable.newq_org,
			R.drawable.newp_org, R.drawable.newn_org, R.drawable.newl_org, R.drawable.newk_org, R.drawable.newj_org,
			R.drawable.newh_org, R.drawable.newg_org, R.drawable.newd_org, R.drawable.newa_org, R.drawable.weibow_org,
			R.drawable.weibop_org, R.drawable.weiboo_org, R.drawable.weibom_org, R.drawable.weiboi_org,
			R.drawable.weiboe_org, R.drawable.weiboc_org, R.drawable.weibob_org, R.drawable.pear_org,
			R.drawable.shengluehao_org, R.drawable.kiss2_org, R.drawable.xx2_org, R.drawable.xc_org, R.drawable.wh_org,
			R.drawable.th_org, R.drawable.jh_org, R.drawable.cshuai_org, R.drawable.cqiexi_org, R.drawable.cmihu_org,
			R.drawable.cmiantan_org, R.drawable.cjiong_org, R.drawable.chan_org, R.drawable.cgaoming_org,
			R.drawable.cdaxiao_org, R.drawable.cbianlian_org, R.drawable.xcjzuoyoukan_org, R.drawable.xcjhuaixiao_org,
			R.drawable.xcjkanrenao_org, R.drawable.xcjkaixin_org, R.drawable.xcjguanzhu_org, R.drawable.xcjjiaoxiu_org,
			R.drawable.xcjwuyu_org, R.drawable.xcjyihuo_org, R.drawable.xcjzhengjing_org, R.drawable.xcjwuliao_org,
			R.drawable.xcjwabikong_org, R.drawable.xcjqidai_org, R.drawable.xcjyaotoukan_org, R.drawable.xcjqinqin_org,
			R.drawable.xcjxiushe_org, R.drawable.xcjbeicui_org, R.drawable.xcjdese_org, R.drawable.xcjlengyan_org,
			R.drawable.xcjjingya_org, R.drawable.xcjweiqu_org, R.drawable.xcjshuaishetou_org,
			R.drawable.xcjyaotoumeng_org, R.drawable.xcjzhuakuang_org, R.drawable.xcjfahuo_org,
			R.drawable.xcjmaimeng_org, R.drawable.xcjshangxin_org, R.drawable.xcjwulian_org,
			R.drawable.xcjzhenjingku_org, R.drawable.xcjyaobai_org, R.drawable.xcjdeyixiao_org,
			R.drawable.xcjfanzao_org, R.drawable.xcjdeyi_org, R.drawable.xcjlianhong_org, R.drawable.lxhxmiao_org,
			R.drawable.lxhxmiao2_org, R.drawable.lxhxbenpao_org, R.drawable.lxhxzou_org, R.drawable.lxhxruguo_org,
			R.drawable.lxhxceng_org, R.drawable.lxhxkuanghuan_org, R.drawable.lxhxfendou_org, R.drawable.lxhxxiao_org,
			R.drawable.lxhxlanyao_org, R.drawable.lxhxdeyi_org, R.drawable.lxhxyou_org, R.drawable.lxhxzhuantou_org,
			R.drawable.lxhxtiaoyue_org, R.drawable.lxhxzhuanti_org, R.drawable.lxhxsahuan_org, R.drawable.lxhxnao_org,
			R.drawable.lxhxnaohuang_org, R.drawable.lxhxdouzhuanquan_org, R.drawable.lxhxhua_org,
			R.drawable.lxhxdese_org, R.drawable.lxhxpenti2_org, R.drawable.lxhxpenti_org, R.drawable.lxhxku_org,
			R.drawable.lxhxsaohui_org, R.drawable.lxhxtingge_org, R.drawable.lxhxkuangchi_org,
			R.drawable.lxhxhuaquan_org, R.drawable.lxhxxianzhuo_org, R.drawable.lxhxshuaya_org,
			R.drawable.lxhxbaozhen_org, R.drawable.lxhxdoubugei_org, R.drawable.lxhxdouzuoyou_org,
			R.drawable.lxhxbianhua_org, R.drawable.lxhxdadishu_org, R.drawable.lxhxxigua_org, R.drawable.lxhxxiu1_org,
			R.drawable.lxhxxiu2_org, R.drawable.lxhxxiu3_org, R.drawable.lxhxxiu4_org, R.drawable.lxhxxiu5_org,
			R.drawable.lxhxxiu6_org, R.drawable.lxhxxiu7_org, R.drawable.lxhxxiu8_org, R.drawable.lxhxgunguo_org,
			R.drawable.lxhxtangzhongqiang_org, R.drawable.lxhxtaoyan_org, R.drawable.lxhxdoushangxia_org,
			R.drawable.lxhxtuxue_org, R.drawable.lxhxbingle_org, R.drawable.lxhxleimu_org, R.drawable.lxhxwuyu_org,
			R.drawable.lxhxwenhao_org, R.drawable.lxhxcemu_org, R.drawable.lxhxjing_org, R.drawable.lxhxtu_org,
			R.drawable.lxhxshiluo_org, R.drawable.lxhxhan_org, R.drawable.lxhxhan1_org, R.drawable.lxhxhen_org,
			R.drawable.lxhxyuannian_org, R.drawable.lxhxshuijiao_org, R.drawable.lxhxqiubiaoyang_org,
			R.drawable.lxhxzhuodi_org, R.drawable.lxhxwuliao_org, R.drawable.lxhxshunmao_org, R.drawable.lxhxhenai_org,
			R.drawable.lxhxbushuang_org, R.drawable.lxhxlaoda_org, R.drawable.lxhxshengrikuaile_org,
			R.drawable.longnianmtjj_org, R.drawable.mango_12_org, R.drawable.w_org, R.drawable.tf_org,
			R.drawable.sc_org, R.drawable.qzdy_org, R.drawable.lx_org, R.drawable.ljf_org, R.drawable.hs2_org,
			R.drawable.gf_org, R.drawable.dyzq_org, R.drawable.ch_org, R.drawable.bb2_org, R.drawable.wind_org,
			R.drawable.sunny_org, R.drawable.snow_org, R.drawable.sh_org, R.drawable.rain, R.drawable.dark_org,
			R.drawable.zxyxchenxuedong_org, R.drawable.zxyxwanzi_org, R.drawable.hqgtangbao_org,
			R.drawable.bbqnxiatian_org, R.drawable.bbqnmengwadajun_org, R.drawable.zxyxtongdawei_org,
			R.drawable.bbqnxuanxuan_org, R.drawable.bbqnkkbaoyou_org, R.drawable.bbqnchulaihai_org,
			R.drawable.huaqianguxiaogu_org, R.drawable.huaqiangusqm_org, R.drawable.hqgzunshangv1_org,
			R.drawable.qixi2015_org, R.drawable.kandiev2_org, R.drawable.kanzhangv2_org, R.drawable.htzchongfang_org,
			R.drawable.flag_org, R.drawable.htzclanfang_org, R.drawable.gqzn_org, R.drawable.chrisbell_org,
			R.drawable.bianpao_org, R.drawable.hongbao1_org, R.drawable.weijin_org, R.drawable.wennuanmaozi_org,
			R.drawable.shoutao_org, R.drawable.hongbao_org, R.drawable.xi_org, R.drawable.liwu_org, R.drawable.r_org,
			R.drawable.diamond_org, R.drawable.dynamicbus_org, R.drawable.travel_org, R.drawable.zxc_org,
			R.drawable.jc_org, R.drawable.sj2_org, R.drawable.camera_org, R.drawable.y_org, R.drawable.dn_org,
			R.drawable.sz_org, R.drawable.yellowmood_org, R.drawable.christree_org, R.drawable.chrishat_org,
			R.drawable.chrisfather_org, R.drawable.chrisocks_org, R.drawable.qixi2016_niulang2_org,
			R.drawable.qixi2016_zhinv2_org, R.drawable.allstar_dp_org, R.drawable.halfstar_dp_org,
			R.drawable.blankstar_dp_org, R.drawable.hb_fahongbao2016_org, R.drawable.hb_qiangdao2016_org,
			R.drawable.bbqnshezhang_org, R.drawable.bbqnxiaogongzhushanshan_org, R.drawable.bbqndidihaohao_org,
			R.drawable.bbqnnina_org, R.drawable.ndgl_org, R.drawable.fuqinjie2015_org, R.drawable.huatongv2_org,
			R.drawable.mdcg_org, R.drawable.lang_org, R.drawable.zv_org, R.drawable.nl_org, R.drawable.gonederland_org,
			R.drawable.gogermany_org, R.drawable.gofrance_org, R.drawable.gocostarica_org, R.drawable.gocolombia_org,
			R.drawable.gobrazil_org, R.drawable.gobelgium_org, R.drawable.goargentina_org, R.drawable.wasjb_org,
			R.drawable.muqinjie_org, R.drawable.mothersday_org, R.drawable.carnation_org, R.drawable.suishoupai2014_org,
			R.drawable.hongyun_org, R.drawable.hongyun_org, R.drawable.hongbaofei2014_org, R.drawable.lavida_org,
			R.drawable.jingnengyang_org, R.drawable.yiqilai_org, R.drawable.weitrip_org, R.drawable.lenovebiaoan_org,
			R.drawable.newvans_org, R.drawable.goshandong_org, R.drawable.goguangdong_org, R.drawable.konca_org,
			R.drawable.kiago_org, R.drawable.shenshou_org, R.drawable.weibo3yr_org, R.drawable.weibovip_org,
			R.drawable.darenanniversary_org, R.drawable.lundunaohuo_org, R.drawable.longniao_org,
			R.drawable.longdan_org, R.drawable.xunlu_org, R.drawable.shfabu_org, R.drawable.red_band_org,
			R.drawable.green_band_org, R.drawable.yinyuehe_org, R.drawable.shoufa_org, R.drawable.jobs_org,
			R.drawable.iphone_org, R.drawable.weibo2zhounian_org, R.drawable.tupianimage_org, R.drawable.zhishujie_org,
			R.drawable.nycake_org, R.drawable.candy_org, R.drawable.nanguatou2_org, R.drawable.pink_org,
			R.drawable.hj_org, R.drawable.wine_org, R.drawable.mooncake3_org, R.drawable.moon1_org,
			R.drawable.blackboard_org, R.drawable.qkl_org, R.drawable.jy_org, R.drawable.j2_org, R.drawable.g_org,
			R.drawable.gz3_org, R.drawable.gz2_org, R.drawable.green_org, R.drawable.gq_org, R.drawable.foot_org,
			R.drawable.clock_org, R.drawable.cha_org, R.drawable.watermelon, R.drawable.umb_org, R.drawable.tv_org,
			R.drawable.tel_org, R.drawable.sun, R.drawable.star_org, R.drawable.shao, R.drawable.music_org,
			R.drawable.movie_org, R.drawable.moon, R.drawable.ktv_org, R.drawable.ice, R.drawable.house_org,
			R.drawable.hat_org, R.drawable.football, R.drawable.flower_org, R.drawable.flower, R.drawable.fan,
			R.drawable.cheer, R.drawable.cafe_org, R.drawable.xyjgongyi_org, R.drawable.xyjfengle_org,
			R.drawable.xyjsajiao_org, R.drawable.xyjtuxue_org, R.drawable.xyjlangxiao_org, R.drawable.xyjzuoyi_org,
			R.drawable.xyjaiya_org, R.drawable.xyjguale_org, R.drawable.xyjniuyangge_org, R.drawable.xyjmeiyan_org,
			R.drawable.xyjlaima_org, R.drawable.xyjceng_org, R.drawable.longnianxyjyu_org, R.drawable.longnianxyjhb_org,
			R.drawable.longnianxyjbai_org, R.drawable.chn_zhuashafa_org, R.drawable.chn_zhenhan_org,
			R.drawable.chn_yun_org, R.drawable.chn_xiayan_org, R.drawable.chn_weinan_org, R.drawable.chn_tian_org,
			R.drawable.chn_liuhan_org, R.drawable.chn_leng_org, R.drawable.chn_laoda_org, R.drawable.chn_keshui_org,
			R.drawable.chn_kelian_org, R.drawable.chn_kafei_org, R.drawable.chn_huaixiao_org, R.drawable.chn_ding_org,
			R.drawable.chn_deyi_org, R.drawable.chn_chonga_org, R.drawable.chn_chixigua_org, R.drawable.chn_buyaoya_org,
			R.drawable.chn_biaolei_org, R.drawable.chn_aini_org, R.drawable.mocshengrikuaile_org,
			R.drawable.moczizhong_org, R.drawable.moczhuangtou_org, R.drawable.moczhuangku_org,
			R.drawable.moczhuanfa_org, R.drawable.moczhongjian_org, R.drawable.mocyun_org, R.drawable.mocxiu_org,
			R.drawable.mocweiguan_org, R.drawable.mocwanan_org, R.drawable.moctantiao_org, R.drawable.mocshihua_org,
			R.drawable.mocshengqi_org, R.drawable.mocqinqinzuo_org, R.drawable.mocqinqinyou_org,
			R.drawable.mocqinqinwen_org, R.drawable.mocqiangwen_org, R.drawable.mocpaizhao_org, R.drawable.mocoutu_org,
			R.drawable.mocmaochu_org, R.drawable.mocluguo_org, R.drawable.mockanqingchu_org, R.drawable.mocjiebing_org,
			R.drawable.mocji_org, R.drawable.mocguilian_org, R.drawable.mocganga_org, R.drawable.mocfuyun_org,
			R.drawable.mocding_org, R.drawable.mocdaku_org, R.drawable.mocdakouchi_org, R.drawable.mocdaji_org,
			R.drawable.mocciyaxiao_org, R.drawable.mocchelian_org, R.drawable.guibao1sikao_org,
			R.drawable.guibao2zhenjing_org, R.drawable.guibao3kuangxiao_org, R.drawable.guibao4lianhong_org,
			R.drawable.guibao5faleng_org, R.drawable.guibao6hualao_org, R.drawable.guibao7chuifa_org,
			R.drawable.guibao8baoku_org, R.drawable.guibao9shangxin_org, R.drawable.guibao10dese_org,
			R.drawable.guibao11meiyan_org, R.drawable.guibao12wugu_org, R.drawable.guibao13tiaomei_org,
			R.drawable.guibao14mojing_org, R.drawable.guibao16mojing_org, R.drawable.guibao17bianlian_org,
			R.drawable.guibao18shanxiao_org, R.drawable.guibao19koubi_org, R.drawable.guibao20koubi_org,
			R.drawable.guibao21baohan_org, R.drawable.guibao22handi_org, R.drawable.guibao23jujue_org,
			R.drawable.guibao24yinying_org, R.drawable.guibao25bixue_org, R.drawable.guibao26outu_org,
			R.drawable.guibao27penxue_org, R.drawable.guibao28leidi_org, R.drawable.guibao29jingya_org,
			R.drawable.guibao30touyun_org, R.drawable.guibao31shanya_org, R.drawable.guibao32shanya_org,
			R.drawable.guibao33juhan_org, R.drawable.guibao34guzhang_org, R.drawable.guibao35zhaohu_org,
			R.drawable.guibao36guzhang_org, R.drawable.guibao37wusuowei_org, R.drawable.guibao38leiji_org,
			R.drawable.guibao39xiexiao_org, R.drawable.guibao40luoben_org, R.drawable.guibao41luoben_org,
			R.drawable.guibao42luoben_org, R.drawable.guibao43judao_org, R.drawable.guibao44hecha_org,
			R.drawable.guibao45yaoshou_org, R.drawable.guibao46bingle_org, R.drawable.guibao47dongshang_org,
			R.drawable.guibao48haoleng_org, R.drawable.guibao49weiqu_org, R.drawable.guibao50fapiao_org,
			R.drawable.guibao51maimeng_org, R.drawable.guibao52changge_org, R.drawable.guibao53chitang_org,
			R.drawable.guibao54guibao_org, R.drawable.guibao55wangwang_org, R.drawable.guibao56tushe_org,
			R.drawable.guibao57gutou_org, R.drawable.guibao58koushui_org, R.drawable.guibao59jingya_org,
			R.drawable.guibao60baoku_org, R.drawable.guibao60jidong_org, R.drawable.lmmzhaocaimao0_org,
			R.drawable.lmmzeixiao0_org, R.drawable.lmmyansu0_org, R.drawable.lmmxiaodizhu0_org,
			R.drawable.lmmwunai0_org, R.drawable.lmmwabisi0_org, R.drawable.lmmtianrandai0_org,
			R.drawable.lmmshengbingle0_org, R.drawable.lmmpukelian0_org, R.drawable.lmmpubuhan0_org,
			R.drawable.lmmmoya0_org, R.drawable.lmmmeitingjian0_org, R.drawable.lmmmeishiba0_org,
			R.drawable.lmmmangran0_org, R.drawable.lmmleiliumanmian0_org, R.drawable.lmmjionghan0_org,
			R.drawable.lmmjingkong0_org, R.drawable.lmmjingdai0_org, R.drawable.lmmjingcha0_org,
			R.drawable.lmmhunluan0_org, R.drawable.lmmhuachi0_org, R.drawable.lmmheshui0_org, R.drawable.lmmheihei0_org,
			R.drawable.lmmhahaha0_org, R.drawable.lmmganxiao0_org, R.drawable.lmmfengle0_org, R.drawable.lmmexin0_org,
			R.drawable.lmmduduzui0_org, R.drawable.lmmdila0_org, R.drawable.lmmdiantou0_org, R.drawable.lmmdanu0_org,
			R.drawable.lmmdajingshise0_org, R.drawable.lmmdaixiao0_org, R.drawable.lmmdacuoxian0_org,
			R.drawable.lmmdabian0_org, R.drawable.lmmbu0_org, R.drawable.lmmbitichong0_org, R.drawable.lmmbaoyuhan0_org,
			R.drawable.lmmawuawu0_org, R.drawable.lmmaiaiai0_org, R.drawable.longnianmk_org,
			R.drawable.cat_zhendanding_org, R.drawable.cat_yunqizhong_org, R.drawable.cat_yi_org,
			R.drawable.cat_yitoushuxian_org, R.drawable.cat_xingxingyan_org, R.drawable.cat_xiaomimi_org,
			R.drawable.cat_xiaodizhu_org, R.drawable.cat_wocuole_org, R.drawable.cat_wei_org,
			R.drawable.cat_tushetou_org, R.drawable.cat_tianrandai_org, R.drawable.cat_taozuile_org,
			R.drawable.cat_shengqile_org, R.drawable.cat_shengbingle_org, R.drawable.cat_renbuliao_org,
			R.drawable.cat_pukelian_org, R.drawable.cat_pubuhan_org, R.drawable.cat_nimeishiba_org,
			R.drawable.cat_neiniumanmian_org, R.drawable.cat_meitingjian_org, R.drawable.cat_kusila_org,
			R.drawable.cat_jionghan_org, R.drawable.cat_jingkongzhong_org, R.drawable.cat_hunluanzhong_org,
			R.drawable.cat_huachishanshan_org, R.drawable.cat_heiheihei_org, R.drawable.cat_hahaha_org,
			R.drawable.cat_ganxiaozhong_org, R.drawable.cat_exinsi_org, R.drawable.cat_duduzui_org,
			R.drawable.cat_danu_org, R.drawable.cat_dajingshise_org, R.drawable.cat_daidai_org,
			R.drawable.cat_dacuoxian_org, R.drawable.cat_bitichong_org, R.drawable.cat_baoyuhan_org,
			R.drawable.cat_awuawu_org, R.drawable.cat_ai_org, R.drawable.cat_aiaiai_org, R.drawable.brddengtui_org,
			R.drawable.brdtantiao_org, R.drawable.brdche_org, R.drawable.brdlingluan_org, R.drawable.brdbenpao_org,
			R.drawable.brdyangwoqizuo_org, R.drawable.brdchuyu_org, R.drawable.brdlianyao_org, R.drawable.brdpi_org,
			R.drawable.brdnaoyang_org, R.drawable.brdlalala_org, R.drawable.brdjuyaling_org, R.drawable.brdpiaohu_org,
			R.drawable.brdpaishou_org, R.drawable.brdheiha_org, R.drawable.brdtabu_org, R.drawable.brdrouyan_org,
			R.drawable.brdzhuanquan_org, R.drawable.brdfeiwen_org, R.drawable.brdtiao_org, R.drawable.brdbazhang_org,
			R.drawable.brdsajiao_org, R.drawable.brdpailian_org, R.drawable.brdhaobao_org, R.drawable.brdpao_org,
			R.drawable.brdxingfen_org, R.drawable.brdxinlongnian_org, R.drawable.brdnianlongnian_org,
			R.drawable.brdlongnian_org, R.drawable.brdjinlongnian_org, R.drawable.brdhelongnian_org,
			R.drawable.ppbshengrikuaile_org, R.drawable.ppbfool_org, R.drawable.ppbshengyi_org, R.drawable.ppbddd_org,
			R.drawable.ppbzaoan_org, R.drawable.ppbxizao_org, R.drawable.ppbtuoguang_org, R.drawable.ppbpengxue_org,
			R.drawable.ppbnienie_org, R.drawable.ppbluozou_org, R.drawable.ppbluowu_org, R.drawable.ppbluguo_org,
			R.drawable.ppbjidong_org, R.drawable.ppbjianxiao_org, R.drawable.ppbguzhang_org, R.drawable.ppbbibi_org,
			R.drawable.ppbkao_org, R.drawable.ppbfakuang_org, R.drawable.ppbkun_org, R.drawable.ppbahaha_org,
			R.drawable.ppbjiangshi_org, R.drawable.ppbshuaizui_org, R.drawable.ppbjiong_org, R.drawable.ppbqusi_org,
			R.drawable.ppbqingtianpili_org, R.drawable.ppba_org, R.drawable.ppbdaku_org, R.drawable.ppbwokan_org,
			R.drawable.ppbsaoshe_org, R.drawable.ppbshaa_org, R.drawable.ppbawu_org, R.drawable.ppbbianfuxia_org,
			R.drawable.ppbgun_org, R.drawable.ppbhuanying_org, R.drawable.ppbkuangchi_org, R.drawable.ppbtaoyan_org,
			R.drawable.ppbainiyo_org, R.drawable.ppbmaimeng_org, R.drawable.ayxzuomianmo_org, R.drawable.ayxzma_org,
			R.drawable.ayxzhenjing_org, R.drawable.ayxyes_org, R.drawable.ayxyanmian_org, R.drawable.ayxwuya_org,
			R.drawable.ayxwunai_org, R.drawable.ayxwanan_org, R.drawable.ayxshengrikuaile_org, R.drawable.ayxsahuan_org,
			R.drawable.ayxno_org, R.drawable.ayxluguo_org, R.drawable.ayxliuhan_org, R.drawable.ayxliubixue_org,
			R.drawable.ayxleisi_org, R.drawable.ayxleiben_org, R.drawable.ayxkuqi_org, R.drawable.ayxkaixin_org,
			R.drawable.ayxkaifanluo_org, R.drawable.ayxjiujie_org, R.drawable.ayxhaixiu_org, R.drawable.ayxguzhang_org,
			R.drawable.ayxgandong_org, R.drawable.ayxfuyun_org, R.drawable.ayxfeiwen_org, R.drawable.ayxdazhaohu_org,
			R.drawable.ayxbuzhuang_org, R.drawable.ayxbenkui_org, R.drawable.km1wenhao_org, R.drawable.km1aini_org,
			R.drawable.km1baikuaixuanzhuan_org, R.drawable.km1heikuaixuanzhuan_org, R.drawable.km1huachi_org,
			R.drawable.km1keai_org, R.drawable.km1qie_org, R.drawable.km1qinqin_org, R.drawable.km1qinqinbaikuai_org,
			R.drawable.km1qinqinheikuai_org, R.drawable.km1wabishi_org, R.drawable.km1wawaku_org,
			R.drawable.km1weiguan_org, R.drawable.km1weiqu_org, R.drawable.km1xiu_org, R.drawable.kmfl_org,
			R.drawable.kmzhentan_org, R.drawable.kmxixi_org, R.drawable.kmwuwu1_org, R.drawable.kmlengxiao_org,
			R.drawable.kmyoujian_org, R.drawable.kmnaozhong_org, R.drawable.kmheng_org, R.drawable.kmwuyu_org,
			R.drawable.kmheikuaibudanding_org, R.drawable.kmhaipa_org, R.drawable.kmwuwu88_org,
			R.drawable.kmtouliang_org, R.drawable.kmwu_org, R.drawable.kmxiadao_org, R.drawable.kmzui_org,
			R.drawable.kmlisha2_org, R.drawable.kmku2_org, R.drawable.kmhan_org, R.drawable.kmzhongdu_org,
			R.drawable.kmdianshi_org, R.drawable.kmkun_org, R.drawable.kmgaoxing_org, R.drawable.kmyaojimao_org,
			R.drawable.kmhaihuaxiao_org, R.drawable.kmhuamao_org, R.drawable.kmhaochi_org, R.drawable.kmai_org,
			R.drawable.kmheihualaodao_org, R.drawable.kmhaochijing_org, R.drawable.kmlaodao_org,
			R.drawable.kmyanjing_org, R.drawable.kmshan_org, R.drawable.kmv_org, R.drawable.kmbudanding_org,
			R.drawable.kmbixue1_org, R.drawable.kmhaoe_org, R.drawable.kmshangchuan_org, R.drawable.kmheihua_org,
			R.drawable.kmbixue_org, R.drawable.kmku_org, R.drawable.kmchou_org, R.drawable.kmxiangji_org,
			R.drawable.kmxi_org, R.drawable.kmdeyi_org, R.drawable.kmnu_org, R.drawable.kmshengqi_org,
			R.drawable.kmdw_org, R.drawable.km1wuxuelei_org, R.drawable.kmps_org, R.drawable.kmchan_org,
			R.drawable.kmxiazai_org, R.drawable.kmx_org, R.drawable.kmqingshu_org, R.drawable.kmkulou_org,
			R.drawable.kmlisha_org, R.drawable.kmjin_org, R.drawable.kmyun_org, R.drawable.kmre_org,
			R.drawable.kmleng_org, R.drawable.kmmao_org, R.drawable.longniankm_org, R.drawable.bofutushetou_org,
			R.drawable.bofulongnian_org, R.drawable.bofuyinxiao_org, R.drawable.bofuyalishanda_org,
			R.drawable.bofuxinhuiyileng_org, R.drawable.bofuxindong_org, R.drawable.bofuxiandanchaoren_org,
			R.drawable.bofushishen_org, R.drawable.bofupiaozikuailai_org, R.drawable.bofunu_org, R.drawable.bofuniu_org,
			R.drawable.bofumengyi_org, R.drawable.bofulei_org, R.drawable.bofukenxigua_org, R.drawable.bofugeili_org,
			R.drawable.bofufafentuqiang_org, R.drawable.bofudousao_org, R.drawable.bofudese_org,
			R.drawable.bofudafeiji_org, R.drawable.bofubianlian_org, R.drawable.bofubengji_org,
			R.drawable.bofubaozao_org, R.drawable.mmxingxingyan_org, R.drawable.mmdagun_org,
			R.drawable.mmshuaimaozi_org, R.drawable.mmshuaipingzi_org, R.drawable.mmniupigu_org,
			R.drawable.mmjidujingya_org, R.drawable.mmlandeli_org, R.drawable.mmwuzuile_org, R.drawable.mmbishini_org,
			R.drawable.mmdagehaqian_org, R.drawable.mmshihua_org, R.drawable.mmqiaodagu_org, R.drawable.mmtankouqi_org,
			R.drawable.mmchuidixiao_org, R.drawable.mmwulian_org, R.drawable.mmkuangliuhan_org,
			R.drawable.mmkoubizi_org, R.drawable.mmleiben_org, R.drawable.mmxianduohua_org, R.drawable.liaobuqi_org,
			R.drawable.guanbuzhao_org, R.drawable.img_2guanbuzhao1_org, R.drawable.ai_org,
			R.drawable.img_2liaobuqiai_org, R.drawable.gbzzhenchuanyue_org, R.drawable.gbzzaishuihui_org,
			R.drawable.gbzwuwu_org, R.drawable.gbzweiqu_org, R.drawable.gbzwananle_org, R.drawable.gbzqifu_org,
			R.drawable.gbzqifule_org, R.drawable.gbzqiexiao_org, R.drawable.gbzqichuangla_org, R.drawable.gbzkun_org,
			R.drawable.gbzjiaban_org, R.drawable.gbzjiabanzhong_org, R.drawable.gbze_org, R.drawable.gbzeyun_org,
			R.drawable.gbzdeyi_org, R.drawable.gbzdaxiao_org, R.drawable.gbzchuanyuele_org, R.drawable.youdiankun_org,
			R.drawable.yes_org, R.drawable.yanhuiqule_org, R.drawable.yalihenda_org, R.drawable.xiuxiu_org,
			R.drawable.xihuang_org, R.drawable.xiaobianpi_org, R.drawable.wunai22_org, R.drawable.tutu_org,
			R.drawable.tushetou_org, R.drawable.touyun_org, R.drawable.tingyinyue_org, R.drawable.shuijiao_org,
			R.drawable.shanshanzi_org, R.drawable.shanshanlu_org, R.drawable.shanshanhui_org,
			R.drawable.shanshanhong_org, R.drawable.shanshanfen_org, R.drawable.paoxiao_org, R.drawable.motou_org,
			R.drawable.meihao_org, R.drawable.lianhongzibao_org, R.drawable.kuqinv_org, R.drawable.kuqinan_org,
			R.drawable.kong_org, R.drawable.jinqingwan_org, R.drawable.jingxi_org, R.drawable.jingdai_org,
			R.drawable.huluobo_org, R.drawable.huangtengquai_org, R.drawable.ganmao_org, R.drawable.fennu_org,
			R.drawable.fendou123_org, R.drawable.faya_org, R.drawable.chunnuanhuakai_org, R.drawable.chouyan_org,
			R.drawable.ang_org, R.drawable.aa_org, R.drawable.zichashuangmu_org, R.drawable.yiwen_org,
			R.drawable.xu_org, R.drawable.wochiwode_org, R.drawable.weiqu_org, R.drawable.v5_org, R.drawable.tiaoxi_org,
			R.drawable.taihaoxiaole_org, R.drawable.shoujian_org, R.drawable.se_org, R.drawable.pen_org,
			R.drawable.nidongde_org, R.drawable.miaomiao_org, R.drawable.meiwei_org, R.drawable.jingkong_org,
			R.drawable.gandong_org, R.drawable.fangkai_org, R.drawable.chidai_org, R.drawable.chelian_org,
			R.drawable.buzhisuocuo_org, R.drawable.baiyan_org, R.drawable.ccfengdiao_org, R.drawable.ccchihuo_org,
			R.drawable.ccyiwen_org, R.drawable.cclaoye_org, R.drawable.cckaixin_org, R.drawable.ccpapa_org,
			R.drawable.ccauv_org, R.drawable.ccbixue_org, R.drawable.ccmeiyou_org, R.drawable.ccyuncai_org,
			R.drawable.ccmeiyan_org, R.drawable.ccbishi_org, R.drawable.ccweiqu_org, R.drawable.ccgeming_org,
			R.drawable.cczhuangqiang_org, R.drawable.ccchuanyue_org, R.drawable.ccheihei_org, R.drawable.ccbuxing_org,
			R.drawable.ccdaku_org, R.drawable.ccshualai_org, R.drawable.ccjidong_org, R.drawable.cckuqi_org,
			R.drawable.ccqinqin_org, R.drawable.ccxinxu_org, R.drawable.ccwudong_org, R.drawable.ccshuqian_org,
			R.drawable.ccbaobao_org, R.drawable.ccshuijiao_org, R.drawable.ccjiangshi_org, R.drawable.ccwocai_org,
			R.drawable.ccyundong_org, R.drawable.ccgongxi_org, R.drawable.ccgechang_org, R.drawable.ccwuyu_org,
			R.drawable.ccyumen_org, R.drawable.ccsikao_org, R.drawable.ccjingya_org, R.drawable.ccdese_org,
			R.drawable.ccbuma_org, R.drawable.ccshengqi_org, R.drawable.ccqitao_org, R.drawable.cchula_org,
			R.drawable.cctoule_org, R.drawable.ccwunai_org, R.drawable.ccmengmian_org, R.drawable.ccsese_org,
			R.drawable.cchaha_org, R.drawable.npgongyi_org, R.drawable.nonoshengrikuaile_org, R.drawable.nonodese_org,
			R.drawable.nonomaishuai_org, R.drawable.nonoyaoshouzhi_org, R.drawable.nonolaiyalaiya_org,
			R.drawable.nonoku_org, R.drawable.nonotiaodou_org, R.drawable.nonojiuxiu_org, R.drawable.nonoshengbing_org,
			R.drawable.nonokaixin_org, R.drawable.nonokanbujianwo_org, R.drawable.nonozhayan_org,
			R.drawable.nonodalibao_org, R.drawable.nonoshuiwangwang_org, R.drawable.nonokiss_org,
			R.drawable.nonoshengdanjie_org, R.drawable.nonotiaowu_org, R.drawable.nonohaixiu_org,
			R.drawable.nonowuyu_org, R.drawable.nonofangpi_org, R.drawable.nonoyun_org, R.drawable.nonoyouzaipao_org,
			R.drawable.nonodahaqian_org, R.drawable.nononiu_org, R.drawable.nonomua_org, R.drawable.nonoganga_org,
			R.drawable.nonopaobu_org, R.drawable.nonozhuanquanquan_org, R.drawable.nonoxinxinyan_org,
			R.drawable.nonoshuijiao_org, R.drawable.nonoxingxingyan_org, R.drawable.nonopaoxiaoqiu_org,
			R.drawable.longnianpanda_org, R.drawable.dinoqiuren_org, R.drawable.dinoleiben_org,
			R.drawable.dinohaixiu_org, R.drawable.dinodengren_org, R.drawable.dinojiong_org, R.drawable.dinokoubi_org,
			R.drawable.dinoxinsui_org, R.drawable.dinosahua_org, R.drawable.dinodiantong_org, R.drawable.dinore_org,
			R.drawable.dinohuaixiao_org, R.drawable.dinoliwu_org, R.drawable.dinoyundao_org, R.drawable.dinoguiyi_org,
			R.drawable.dinokeshui_org, R.drawable.dinoanwei_org, R.drawable.dinozaijian_org,
			R.drawable.dinotiantong_org, R.drawable.dinobuxie_org, R.drawable.dinozaoan_org, R.drawable.dinogaoxing_org,
			R.drawable.dinotouxiang_org, R.drawable.dinoguilian_org, R.drawable.dinochifan_org,
			R.drawable.dinoshiwang_org, R.drawable.dinoshuqian_org, R.drawable.dinodani_org,
			R.drawable.dinokuangjiao_org, R.drawable.dinotuxue_org, R.drawable.dinoweiqu_org,
			R.drawable.dinohuaquan_org, R.drawable.dinofanu_org, R.drawable.dinochijing_org, R.drawable.dinohejiu_org,
			R.drawable.dinoyaoshoupa_org, R.drawable.dinochoumei_org, R.drawable.dinokunhuo_org,
			R.drawable.dinoxuyuan_org, R.drawable.dinodagun_org, R.drawable.yzwodao_org, R.drawable.yzzhuangboli_org,
			R.drawable.yzlinyu_org, R.drawable.yznani_org, R.drawable.yzhuanhu_org, R.drawable.yzpaizhuozi_org,
			R.drawable.yzguanglun_org, R.drawable.yzwawajiao_org, R.drawable.yzqiunile_org, R.drawable.yzfangun_org,
			R.drawable.yztouzhexiao_org, R.drawable.yzye_org, R.drawable.yztouxiang_org, R.drawable.yzchoufeng_org,
			R.drawable.yzoye_org, R.drawable.yzsahua_org, R.drawable.yzbaozhentou_org, R.drawable.yzshuaishoujuan_org,
			R.drawable.yzyoubianliangle_org, R.drawable.yzrenne_org, R.drawable.yzshaxixi_org, R.drawable.yzza_org,
			R.drawable.yzzhaocaimao_org, R.drawable.yzshanshanzi_org, R.drawable.yzbune_org, R.drawable.yzpaipigu_org,
			R.drawable.yzweiquku_org, R.drawable.yztingge_org, R.drawable.yzchigua_org, R.drawable.yzhaowa_org,
			R.drawable.yzlaikankan_org, R.drawable.yzjiaotangwu_org, R.drawable.yzfangpi_org,
			R.drawable.yzchipingguo_org, R.drawable.yztaihaole_org, R.drawable.yzhaojinzhang_org, R.drawable.weisuo_org,
			R.drawable.tiaomei_org, R.drawable.tiaodou_org, R.drawable.qinerduo_org, R.drawable.meiyan_org,
			R.drawable.maogepao_org, R.drawable.jiongerduo_org, R.drawable.guilian_org, R.drawable.fangdian_org,
			R.drawable.beiju_org, R.drawable.touch_org, R.drawable.sweat_org, R.drawable.suprise_org,
			R.drawable.supcry_org, R.drawable.stareyes_org, R.drawable.sleepy_org, R.drawable.sick_org,
			R.drawable.plus1_org, R.drawable.pipioye_org, R.drawable.muamua_org, R.drawable.mianchou_org,
			R.drawable.laugh_org, R.drawable.knead_org, R.drawable.jiong_org, R.drawable.honeyoye_org,
			R.drawable.happy_org, R.drawable.handkerchief_org, R.drawable.go_org, R.drawable.dizzy_org,
			R.drawable.cry_org, R.drawable.coverface_org, R.drawable.angery_org, R.drawable.img_886_org,
			R.drawable.byz2_org, R.drawable.ssz2_org, R.drawable.syz2_org, R.drawable.szz2_org, R.drawable.tpz2_org,
			R.drawable.txz2_org, R.drawable.spz2_org, R.drawable.cnz2_org, R.drawable.jnz2_org, R.drawable.jxz2_org,
			R.drawable.leo2_org, R.drawable.mjz2_org, R.drawable.txz_org, R.drawable.tpz_org, R.drawable.szz_org,
			R.drawable.syz_org, R.drawable.ssz_org, R.drawable.spz_org, R.drawable.mjz_org, R.drawable.leo_org,
			R.drawable.jxz_org, R.drawable.jnz_org, R.drawable.cnz_org, R.drawable.byz_org, R.drawable.aixincd_org,
			R.drawable.zxhdese_org, R.drawable.xiaoheweixiao_org, R.drawable.xiaoheweiqu_org, R.drawable.xiaohetua_org,
			R.drawable.xiaoheshengqi_org, R.drawable.xiaoheliubiti_org, R.drawable.xiaohekuqi_org,
			R.drawable.xiaohehan_org, R.drawable.xiaohefadai_org, R.drawable.xiaohebulini_org,
			R.drawable.xiaohebishi_org, R.drawable.fanzao_org, R.drawable.ciya_org, R.drawable.youqian_org,
			R.drawable.weixiao_org, R.drawable.shuaibao_org, R.drawable.shengqi_org, R.drawable.shengbing_org,
			R.drawable.semimi_org, R.drawable.pilao_org, R.drawable.miao_org, R.drawable.ku_org, R.drawable.kelian_org,
			R.drawable.jinzhang_org, R.drawable.jingya_org, R.drawable.jidong_org, R.drawable.jianqian_org,
			R.drawable.han_org, R.drawable.fendou_org, R.drawable.xrdz_org, R.drawable.whh_org, R.drawable.tq_org,
			R.drawable.sjdj_org, R.drawable.q_org, R.drawable.pz_org, R.drawable.pp_org, R.drawable.nh_org,
			R.drawable.mb2_org, R.drawable.lg_org, R.drawable.lb_org, R.drawable.lbs_org, R.drawable.kiss_org,
			R.drawable.kb_org, R.drawable.jgwb_org, R.drawable.hxgw_org, R.drawable.gx3_org, R.drawable.gg_org,
			R.drawable.fd_org, R.drawable.fc_org, R.drawable.dy_org, R.drawable.cn_org, R.drawable.cf_org,
			R.drawable.ceg_org, R.drawable.cdyn_org, R.drawable.bz2_org, R.drawable.bt_org, R.drawable.bs3_org,
			R.drawable.bgws_org, R.drawable.bf_org, R.drawable.bdw_org, R.drawable.bco_org, R.drawable.yeah_org,
			R.drawable.xh_org, R.drawable.xd_org, R.drawable.wl_org, R.drawable.gx_org, R.drawable.gx2_org,
			R.drawable.gd_org, R.drawable.fn2_org, R.drawable.d2_org, R.drawable.bx_org, R.drawable.longniandx_org,
			R.drawable.daxiongzhadan_org, R.drawable.daxiongxizao_org, R.drawable.daxiongwozhua_org,
			R.drawable.daxiongshuluo_org, R.drawable.daxiongshuaya_org, R.drawable.daxiongsha_org,
			R.drawable.daxiongshai_org, R.drawable.daxiongpaomeiyan_org, R.drawable.daxiongpaipaishou_org,
			R.drawable.daxiongoye_org, R.drawable.daxiongniu_org, R.drawable.daxiongmeiyou_org,
			R.drawable.daxiongmaimeng_org, R.drawable.daxionglianhong_org, R.drawable.daxiongleibenxiong_org,
			R.drawable.daxiongjiayouxiong_org, R.drawable.daxiongjiaotache_org, R.drawable.daxionghuaxin_org,
			R.drawable.daxionghuanle_org, R.drawable.daxionghuaban_org, R.drawable.daxiongdao_org,
			R.drawable.daxiongchaoren_org, R.drawable.daxiongbao_org, R.drawable.daxiongai_org,
			R.drawable.lxhwahaha_org, R.drawable.lxhzhuanfa_org, R.drawable.lxhdeyidixiao_org, R.drawable.lxhxixi_org,
			R.drawable.lxhtouxiao_org, R.drawable.lxhtongku_org, R.drawable.lxhjuhan_org, R.drawable.lxhkoubishi_org,
			R.drawable.lxhqiuguanzhu_org, R.drawable.lxhv5_org, R.drawable.lxhweiguan_org,

	};
}
